name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          flex \
          bison \
          libelf-dev \
          libssl-dev \
          bc \
          dwarves \
          wget
    - name: Setup environment
      run: ./scripts/setup_env.sh
    - name: Build
      run: |
        cd src
        make QEMU_BUILD=1
